# Generated by Django 3.0 on 2020-01-13 16:51

from django.db import migrations, models
import levstik.models.winner


class Migration(migrations.Migration):

    dependencies = [
        ('levstik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ('-awarded_date',)},
        ),
        migrations.AddField(
            model_name='winner',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to=levstik.models.winner.file_path, validators=[levstik.models.winner.max_file_size]),
        ),
    ]
