# Generated by Django 3.0 on 2020-01-13 17:28

from django.db import migrations, models
import levstik.models.winner


class Migration(migrations.Migration):

    dependencies = [
        ('levstik', '0002_auto_20200113_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to=levstik.models.winner.file_path, validators=[levstik.models.winner.max_file_size]),
        ),
    ]
